pluginManagement {
    repositories {
        mavenLocal {
            content {
                includeGroupByRegex 'be\\.elevenways(?:\\..*)?'
            }
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'be.elevenways.protoblast.settings' version '0.1.0-SNAPSHOT'
}

rootProject.name = 'sketerm-java'
